In [1]:
import pandas as pd
import numpy as np

In [9]:
covid19_data = pd.read_csv('covid19.csv', na_values = [''])
covid19_data.dropna(axis = 0, inplace = True)
X = covid19_data.iloc[:, 2:9]

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 4)
X = pca.fit_transform(X)
print(X)

[[ 2.86646008e+01 -4.46716534e+00 -1.78446266e+00 -7.04042232e-01]
 [ 4.71305103e+00 -1.99299519e+00 -7.57910551e-02  4.16795034e+00]
 [ 1.01114010e+01 -8.28369772e-01  7.03458898e-01  1.00653181e+00]
 [ 3.93237833e+00 -5.70115371e-01 -5.87390515e-03 -1.02537159e-01]
 [ 6.35347966e+00  1.41195566e+00  1.44317283e+00 -1.31523671e+00]
 [ 3.43431127e+00  1.28482804e+00  7.07522513e-01  3.78788185e-01]
 [ 2.01567614e+00  2.04423144e+00  3.31430432e-01  1.13122410e+00]
 [ 3.43229690e+00  1.58273874e+00  1.33418357e+00  3.67639619e-01]
 [ 1.37472038e+00 -1.25914919e-01 -5.43160139e-01  3.33785399e-01]
 [ 2.91196817e+00  4.86588179e-02  9.85015798e-01 -7.49105741e-01]
 [ 2.62697757e+00  1.10465241e+00  5.68818711e-01 -6.61407987e-02]
 [ 1.89032185e+00  1.33745440e+00  4.07319183e-01  4.57900310e-01]
 [ 5.27591382e+00 -6.84783467e-03  3.38657386e+00 -1.14704054e+00]
 [ 1.62105601e+00  1.23338683e+00  5.26673401e-01  6.07218248e-02]
 [ 1.73972786e+00  3.80076819e-01  9.93605147e-01 -3.31265475e